//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correlativo
    {
        public string id_dtd { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
        public int id { get; set; }
    
        public virtual DetalleTipoDocumento DetalleTipoDocumento { get; set; }
    }
}
