//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.DocumentoDetalles = new HashSet<DocumentoDetalle>();
        }
    
        public int id_persona { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
        public System.DateTime fecha { get; set; }
        public string observaciones { get; set; }
        public int id_usuario { get; set; }
        public System.DateTime fecha_grabado { get; set; }
        public int estado { get; set; }
        public string id_dtd { get; set; }
    
        public virtual DetalleTipoDocumento DetalleTipoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoDetalle> DocumentoDetalles { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
    }
}
