//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoDetalle
    {
        public string id_dtd { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
        public int id_persona { get; set; }
        public int item { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Kardex Kardex { get; set; }
    }
}
