//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        public string id_dtd { get; set; }
        public string serie { get; set; }
        public string numero { get; set; }
        public int id_persona { get; set; }
        public int item { get; set; }
        public System.DateTime fecha { get; set; }
        public int id_producto { get; set; }
        public decimal ingreso { get; set; }
        public decimal salida { get; set; }
        public decimal saldo { get; set; }
        public decimal ingreso_val { get; set; }
        public decimal salida_val { get; set; }
        public decimal saldo_val { get; set; }
        public decimal costo_promedio { get; set; }
    
        public virtual DocumentoDetalle DocumentoDetalle { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
