//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tienda
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TiendaEntities : DbContext
    {
        public TiendaEntities()
            : base("name=TiendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Correlativo> Correlativoes { get; set; }
        public virtual DbSet<DetalleTipoDocumento> DetalleTipoDocumentoes { get; set; }
        public virtual DbSet<Documento> Documentoes { get; set; }
        public virtual DbSet<DocumentoDetalle> DocumentoDetalles { get; set; }
        public virtual DbSet<Kardex> Kardexes { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
    }
}
